// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQYTRxT9_8314D9cDxe3dFrXccQzefj94',
    appId: '1:481043671937:web:0895372c0ac97f2d6e5680',
    messagingSenderId: '481043671937',
    projectId: 'flutterfire-e33f9',
    authDomain: 'flutterfire-e33f9.firebaseapp.com',
    storageBucket: 'flutterfire-e33f9.appspot.com',
    measurementId: 'G-L34WSJJMXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKaWTMpCQ1YnqDvgTzP30mM0PAG1MksOs',
    appId: '1:481043671937:android:564802e0d9d92f7a6e5680',
    messagingSenderId: '481043671937',
    projectId: 'flutterfire-e33f9',
    storageBucket: 'flutterfire-e33f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYsKDTcvjH0vfIKB2H1DOCV75AVDGKFE',
    appId: '1:481043671937:ios:bbbe7f2a556afb836e5680',
    messagingSenderId: '481043671937',
    projectId: 'flutterfire-e33f9',
    storageBucket: 'flutterfire-e33f9.appspot.com',
    iosBundleId: 'com.example.billGeneration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQYsKDTcvjH0vfIKB2H1DOCV75AVDGKFE',
    appId: '1:481043671937:ios:bbbe7f2a556afb836e5680',
    messagingSenderId: '481043671937',
    projectId: 'flutterfire-e33f9',
    storageBucket: 'flutterfire-e33f9.appspot.com',
    iosBundleId: 'com.example.billGeneration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQYTRxT9_8314D9cDxe3dFrXccQzefj94',
    appId: '1:481043671937:web:e58586399a200ae46e5680',
    messagingSenderId: '481043671937',
    projectId: 'flutterfire-e33f9',
    authDomain: 'flutterfire-e33f9.firebaseapp.com',
    storageBucket: 'flutterfire-e33f9.appspot.com',
    measurementId: 'G-W8ZSC5QNGT',
  );
}
